version: '3.7'
services:

  wdm-k8s-hello:
    container_name: wdm-k8s-hello
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    command: npm run devserverstart
    volumes:
      - './:/home/hellow'
      - '/home/hellow/node_modules'
    ports:
      - "23033:8080"
