version: '3.7'
services:

  node-ci-template:
    container_name: node-ci-template
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    command: npm run devserverstart
    volumes:
      - './:/home/exampleadm'
      - '/home/exampleadm/node_modules'
    ports:
      - "23033:8080"
